source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa

target 'ToolsApp' do
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'XHLaunchAd' #开屏广告三方库，地址：https://github.com/CoderZhuXH/XHLaunchAd
  pod 'FMDB'
  pod 'Masonry'
  pod 'ZipArchive'
  pod 'fishhook'
  pod 'MSWeakTimer'
  pod 'MJRefresh'
end
